### ISSUE TITLE
Conflict with LapisReserve

### ISSUE THREAD

**Issue by Neubulae** [Safrodev/Apotheosis-Fabric#18]
The enchantment table cannot be opened with Lapis Reserve's presence:
```
[18:50:55] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@52bf6cc1, suppressing error
java.lang.NullPointerException: Cannot invoke "safro.apotheosis.util.FloatReferenceHolder.set(float)" because "this.eterna" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3) ~[?:?]
	at safro.apotheosis.ench.table.ApothEnchantContainer.lambda$gatherStats$3(ApothEnchantContainer.java:251) ~[apotheosis-0.2.81.jar:?]
	at net.minecraft.class_3914$2.get(class_3914.java:22) ~[client-intermediary.jar:?]
	at safro.apotheosis.ench.table.ApothEnchantContainer.gatherStats(ApothEnchantContainer.java:228) ~[apotheosis-0.2.81.jar:?]
	at safro.apotheosis.ench.table.ApothEnchantContainer.lambda$slotsChanged$1(ApothEnchantContainer.java:163) ~[apotheosis-0.2.81.jar:?]
	at net.minecraft.class_3914$2.get(class_3914.java:22) ~[client-intermediary.jar:?]
	at safro.apotheosis.ench.table.ApothEnchantContainer.onContentChanged(ApothEnchantContainer.java:160) ~[apotheosis-0.2.81.jar:?]
	at net.minecraft.class_1718$1.markDirty(class_1718.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.inventory.SimpleInventory.redirect$fha000$fabric_redirectMarkDirty(SimpleInventory:1043) ~[?:?]
	at net.minecraft.inventory.SimpleInventory.setStack(SimpleInventory:140) ~[?:?]
	at net.minecraft.screen.slot.Slot.setStack(Slot:61) ~[?:?]
	at net.minecraft.screen.EnchantmentScreenHandler.handler$hff000$open(EnchantmentScreenHandler:2530) ~[?:?]
	at net.minecraft.screen.EnchantmentScreenHandler.<init>(EnchantmentScreenHandler:92) ~[?:?]
	at safro.apotheosis.ench.table.ApothEnchantContainer.<init>(ApothEnchantContainer.java:62) ~[apotheosis-0.2.81.jar:?]
	at net.minecraft.block.EnchantingTableBlock.mdcc0c58$lambda$apothEnchMenu$0$0(EnchantingTableBlock:1039) ~[?:?]
	at net.minecraft.screen.SimpleNamedScreenHandlerFactory.createMenu(SimpleNamedScreenHandlerFactory:25) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.openHandledScreen(ServerPlayerEntity:1031) ~[?:?]
	at net.minecraft.block.EnchantingTableBlock.onUse(EnchantingTableBlock:87) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:939) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.redirect$ckb000$activateWithOptionalCactus(ServerPlayerInteractionManager:4029) ~[?:?]
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:336) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1081) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.redirect$cam000$redirectExecuteTask(ThreadExecutor:521) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:17288) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$chd000$modifiedRunLoop(MinecraftServer:5405) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Safrodev** [comment]
Mods that mixin to the Enchantment Table features won't work with Apotheosis unfortunately. There isn't much I can do so you will have to either uninstall Apotheosis or Lapis Reserve.

**Comment by Neubulae** [comment]
yeah but how about adding a feature of lapis reservoir within the table? or that's beyond scope due to upstream?
